version: 0.2

phases:
  pre_build:
    commands:
      aws ecr get-login-password --endpoint-url ${AccountId}.dkr.ecr.${Region}.amazonaws.com/${Repo} | docker login --username AWS --password-stdin ${AccountId}.dkr.ecr.${Region}.amazonaws.com
  build:
    commands:
      IMAGE_NAME="test-coworking-analytics"
      docker build -t ${IMAGE_NAME} .
      docker tag ${IMAGE_NAME} ${AccountId}.dkr.ecr.${Region}.amazonaws.com/${Repo}:${CODEBUILD_BUILD_NUMBER}
  post_build:
    commands:
      docker push ${AccountId}.dkr.ecr.${Region}.amazonaws.com/${Repo}:${CODEBUILD_BUILD_NUMBER}